# Generated by Django 3.1 on 2021-01-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
                ('category', models.CharField(choices=[('WOMEN', 'Women'), ('MEN', 'Men'), ('KIDS', 'Kids')], max_length=5, null=True)),
                ('Type', models.CharField(choices=[('CASUAL', 'Casual'), ('COOPERATE', 'Cooperate')], max_length=9, null=True)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('image', models.ImageField(default='default.jpg', height_field=400, upload_to='images/', width_field=300)),
            ],
        ),
    ]
