# Generated by Django 3.1 on 2021-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bestseller_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratingList',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
