# Generated by Django 3.1 on 2021-01-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_ratinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labelClass',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labelColor',
            field=models.CharField(blank=True, choices=[('new', 'Green'), ('stockout', 'Grey'), ('stockblue', 'Blue'), ('sale', 'Red')], max_length=10, null=True),
        ),
    ]
