# Generated by Django 3.1 on 2021-01-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210118_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='productType',
        ),
    ]
