# Generated by Django 3.1.5 on 2021-01-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210120_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ip',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='cart',
            field=models.ManyToManyField(to='main.CartItem'),
        ),
    ]
