# Generated by Django 3.1.5 on 2021-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210122_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='totalCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
