# Generated by Django 3.1.5 on 2021-01-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210122_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
