# Generated by Django 3.1.5 on 2021-01-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userdata_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCost', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cart', models.ManyToManyField(to='main.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userdata')),
            ],
        ),
    ]
