# Generated by Django 3.1.5 on 2021-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='notes',
        ),
        migrations.AddField(
            model_name='userdata',
            name='display_order_taken_notification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
