# Generated by Django 3.1.5 on 2021-01-23 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210123_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Created'), (2, 'In Progress'), (3, 'Delivered'), (4, 'Cancelled')], default=1, max_length=10),
        ),
    ]
