# Generated by Django 3.1.5 on 2021-01-23 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('WAITING', 'Waiting'), ('FINISHED', 'Finished')], default='NEW', max_length=15),
        ),
    ]
