# Generated by Django 3.1.5 on 2021-01-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210123_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userdata'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
